[project]
name = "oss-finalpj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "mediapipe>=0.10.14",
    "numpy>=2.3.4",
    "opencv-python-headless>=4.11.0.86",
    "setuptools>=80.9.0",
]
